# docker-compose.yml

version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: rag_qdrant_db
    ports:
      - "6333:6333"  # Port สำหรับ gRPC (LlamaIndex ใช้)
      - "6334:6334"  # Port สำหรับ REST API (ใช้ดู Dashboard)
    volumes:
      - ./qdrant_storage:/qdrant/storage  # เก็บข้อมูลลง disk กันหาย